variables:
  DOCKER_REPO: gitlab.askanna.io:4567/askanna/askanna-frontend
stages:
  - test
  - build
  - deploy
  - cleanup

build_dist:
  image: node:lts-alpine
  tags:
    - normal
  script:
    - npm ci
    - npm run build

build_docker:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG -f compose/production/Dockerfile .
    - docker push ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG
  except:
    - beta

build_docker:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - cp .env.beta .env.production.local
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG -f compose/production/Dockerfile .
    - docker push ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG
  only:
    - beta
    
stop_review:
  variables:
    GIT_STRATEGY: none
  stage: cleanup
  image: curlimages/curl
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  tags:
    - normal
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=frontend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=undeploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}
  except:
    - master

.deploy: &deploy
  variables:
    GIT_STRATEGY: none
  image: curlimages/curl
  stage: deploy
  tags:
    - normal
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=frontend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=deploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}

deploy_branch:
  <<: *deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://${CI_ENVIRONMENT_SLUG}-fe.askanna.eu
    on_stop: stop_review
  except:
    refs:
      - master

deploy_master:
  <<: *deploy
  environment:
    name: master
    url: https://askanna.eu
  only:
    refs:
      - master
    