tasks:
  - name: NPM Dev
    init: |
      ln -s .env.development .env.production.local
      npm install && npm run build
    command: npm run dev
  - name: Git
    command: |
      [[ -n $GPG_KEY ]] && [[ -n $GPG_SIGNING_KEY ]] \
        && echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf \
        && gpg --verbose --batch --import <(echo $GPG_KEY|base64 -d) \
        && git config --global user.signingkey $GPG_SIGNING_KEY \
        && git config --global commit.gpgsign true \
        && echo '>> Commits will be signed with a GPG key'

ports:
  - name: AskAnna Frontend Dev
    port: 5173
    onOpen: open-browser
  - name: AskAnna Frontend Preview
    port: 4173
    onOpen: open-browser

vscode:
  extensions:
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - DavidAnson.vscode-markdownlint
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - octref.vetur
