variables:
  DOCKER_REPO: $CI_REGISTRY_IMAGE
  ENVIRONMENT_DOMAIN: askanna.eu

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - build
  - deploy
  - cleanup

build_dist:
  image: node:lts-alpine
  stage: test
  tags:
    - kubernetes
  script:
    - npm ci
    - npm run build

code_quality:
  stage: test
  tags:
    - docker

build_docker:
  stage: build
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/compose/Dockerfile --destination ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG
  only:
    - master

build_docker_review:
  stage: build
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cp .env.review .env.production.local
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/compose/Dockerfile --destination ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG
  only:
    - branches
  except:
    - beta
    - master

build_docker_beta:
  stage: build
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cp .env.beta .env.production.local
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/compose/Dockerfile --destination ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG
  only:
    - beta

.deploy: &deploy
  variables:
    GIT_STRATEGY: none
  image: curlimages/curl
  stage: deploy
  tags:
    - kubernetes
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=frontend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=deploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}

deploy_master:
  <<: *deploy
  environment:
    name: master
    url: https://${ENVIRONMENT_DOMAIN}
  only:
    - master

deploy_beta:
  <<: *deploy
  environment:
    name: beta
    url: https://beta.${ENVIRONMENT_DOMAIN}
  only:
    - beta

deploy_review:
  <<: *deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://${CI_ENVIRONMENT_SLUG}-fe.${ENVIRONMENT_DOMAIN}
    on_stop: stop_review
    auto_stop_in: 2 weeks
  only:
    - branches
  except:
    - master
    - beta

stop_review:
  variables:
    GIT_STRATEGY: none
  stage: cleanup
  image: curlimages/curl
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  tags:
    - kubernetes
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=frontend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=undeploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}
  only:
    - branches
  except:
    - master
    - beta
