variables:
  GCP_PROJECT: askanna-services
  GKE_CLUSTER_NAME: review-and-runners
  GKE_CLUSTER_ZONE: europe-west1-d
  MASTER_DOMAIN: askanna.eu
  BETA_DOMAIN: beta.askanna.eu
  DEVOPS_DOMAIN: frontend.askanna.dev
  DOCKER_BASE_IMAGE: $CI_REGISTRY_IMAGE/base:$CI_COMMIT_REF_SLUG
  DOCKER_REVIEW: $CI_REGISTRY_IMAGE/review:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

stages:
  - build-base
  - build-deploy
  - test
  - deploy
  - cleanup

include:
  - template: Code-Quality.gitlab-ci.yml

# To use Kaniko extend the job and set variable for DOCKER_DESTINATION and DOCKERFILE
.use-kaniko:
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/compose/Dockerfile.production
    DOCKER_DESTINATION: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --destination $DOCKER_DESTINATION

build_base:
  stage: build-base
  extends: .use-kaniko
  variables:
    DOCKER_FILE: $CI_PROJECT_DIR/compose/Dockerfile.base
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --destination $DOCKER_BASE_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - compose/Dockerfile.base
        - package.json
        - package-lock.json
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

build_master:
  stage: build-deploy
  extends: .use-kaniko
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
  only:
    - master

build_review:
  stage: build-deploy
  extends:
    - .use-kaniko
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
  script:
    - cp .env.review .env.production.local
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --destination $DOCKER_REVIEW --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE
  only:
    - branches
  except:
    - beta
    - master

build_beta:
  stage: build-deploy
  extends:
    - .use-kaniko
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
  script:
    - cp .env.beta .env.production.local
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE --destination $DOCKER_DESTINATION --build-arg BASE_IMAGE=$DOCKER_BASE_IMAGE
  only:
    - beta

test_package_lock:
  stage: test
  image: node:lts-alpine
  needs: []
  script:
    - npm i -g package-lock-check
    - npx package-lock-check

.deploy:
  stage: deploy
  image: curlimages/curl
  tags:
    - kubernetes
  variables:
    GIT_STRATEGY: none
    ASKANNA_DEPLOY_BRANCH: main
    ASKANNA_DEPLOY_PRODUCT: askanna-frontend
  script:
    - curl -X POST -F token=${CI_JOB_TOKEN} -F ref=${ASKANNA_DEPLOY_BRANCH} -F variables[product]=${ASKANNA_DEPLOY_PRODUCT} -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=deploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${ASKANNA_DEPLOY_TRIGGER}

deploy_master:
  extends: .deploy
  rules:
    - if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main")
      when: manual
  environment:
    name: master
    url: https://${MASTER_DOMAIN}

deploy_beta:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "beta"
      when: manual
  environment:
    name: beta
    url: https://${BETA_DOMAIN}

deploy_review:
  stage: deploy
  image: gitlab.askanna.io:4567/askanna/services/helm
  needs:
    - job: build_review
  rules:
    - if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "beta" || $CI_COMMIT_TAG)
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$DEVOPS_DOMAIN
    on_stop: stop_review
    auto_stop_in: 2 weeks
  tags:
    - kubernetes
  script:
    - init_k8s
    - helm upgrade
      --install
      --set app.image="$DOCKER_REVIEW"
      --set app.host="$CI_ENVIRONMENT_SLUG.$DEVOPS_DOMAIN"
      --set deployment.minReplicas=1
      --wait
      $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
      ./k8s-chart

stop_review:
  stage: cleanup
  image: gitlab.askanna.io:4567/askanna/services/helm
  needs:
    - job: deploy_review
  rules:
    - if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "beta")
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  allow_failure: true
  tags:
    - kubernetes
  script:
    - init_k8s
    - helm uninstall $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG

.functions: &functions |
  # Functions
  function init_k8s() {
      gcloud auth activate-service-account --project $GCP_PROJECT --key-file $GCP_SERVICE_ACCOUNT_FILE_AA_SERVICES
      gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT
  }

before_script:
  - *functions
