tasks:
  - name: NPM Serve
    init: npm install && npm run build
    command: npm run serve
  - command: |
      [[ -n $GPG_KEY ]] && [[ -n $GPG_SIGNING_KEY ]] \
        && echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf \
        && gpg --verbose --batch --import <(echo $GPG_KEY|base64 -d) \
        && git config --global user.signingkey $GPG_SIGNING_KEY \
        && git config --global commit.gpgsign true \
        && echo '>> Commits will be signed with a GPG key'

ports:
  - name: AskAnna Frontend
    port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - DavidAnson.vscode-markdownlint
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - octref.vetur
