version: '3'

services:
  frontend:
    build:
      context: .
      target: base-stage
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
