# This file should be used as override for default config.
# It extends the service definitions to serve "built" code
# https://docs.docker.com/compose/extends/
#   $ ln -s docker-compose.production.yml docker-compose.override.yml

version: '3'

services:
  frontend:
    build:
      target: production-stage
    environment:
      VIRTUAL_HOST: askanna.127-0-0-1.nip.io

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
