version: "3"

services:
  frontend:
    image: node:lts-alpine
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        npx cross-env DEBUG=unplugin-vue-components:* vite --host
    volumes:
      - .:/app
    ports:
      - 5173:5173
