version: "3"

services:
  frontend:
    image: node:lts-alpine
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev-with-host
    volumes:
      - .:/app
    ports:
      - 5173:5173
