# This file should be used as override for default config.
# It extends the service definitions to use locally exposed ports
# and mounted volumes.
# https://docs.docker.com/compose/extends/
#   $ ln -s docker-compose.local.yml docker-compose.override.yml

version: '3'

services:
  frontend:
    volumes:
      - .:/app
    ports:
      - "8080:8080"
