---
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: askanna:local
    environment:
      VIRTUAL_HOST: askanna.localhost

  backend:
    image: jwilder/whoami 
    environment:
      VIRTUAL_HOST: api.askanna.localhost

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
